version: '3.9'

services:
  identity-api:
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    ports:
      - "8090:80"
    depends_on:
      - postgres
    env_file:
      env.development
    environment:
      - SqlServerConnectionString=Server=host.docker.internal;Database=Identity;User Id=sa;Password='YourPassword123!';Trust Server Certificate=true;
      - PostgreSqlConnectionString=Host=host.docker.internal;Database=identity;Username=identity;Password='IdentityPassword@';
    networks:
      - internalNetwork

  skillhub-api:
    build:
      context: .
      dockerfile: src/SkillHub.API/Dockerfile
    ports:
      - "8091:80"
    depends_on:
      - postgres
    env_file:
      env.development
    environment:
      - SqlServerConnectionString=Server=host.docker.internal;Database=SkillHub;User Id=sa;Password='YourPassword123!';Trust Server Certificate=true;
      - PostgreSqlConnectionString=Host=host.docker.internal;Database=skillhub;Username=skillhub;Password='skillhubPassword@';
    networks:
      - internalNetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: myuser
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internalNetwork

volumes:
  postgresql_data:

networks:
  internalNetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1