POST {{api}}/api/categories
#Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJGcmVlbGFuY2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI1ODMyZGU1Mi00MWU4LTQwZjEtODAyZS1hZGUwNWQzMjY4MDgiLCJleHAiOjE2ODc4OTg0MzAsImlzcyI6Imh0dHBzOi8vbG9jYWxob3N0OjYwMDEiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIn0.jHn-58neNsJG0FisZNc8dVqt7l-36hXhvCpV9p3jMOw
Content-Type: application/json

{
  "Title": "test"
}

###

GET {{api}}/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJGcmVlbGFuY2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZWlkZW50aWZpZXIiOiI1ODMyZGU1Mi00MWU4LTQwZjEtODAyZS1hZGUwNWQzMjY4MDgiLCJleHAiOjE2ODc5MDI4NzQsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NzY1NCIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEifQ.jj9cBG8eM4vE2InPhTqfQXXe67bMB8YVRHrgFSKhSKg
Content-Type: application/json