### Login
POST {{identity}}/auth/login
Content-Type: application/json

{
  "userName": "GogiMamu",
  "password": "GogiMamu1@"
}

### Register
POST {{identity}}/auth/register
Content-Type: application/json

{
  "username": "Gogimamu8",
  "Email": "gogimamu8@gmail.com",
  "Role": 1,
  "password": "GogiMamu1@"
}

### Get User Internally
GET {{identity}}/user
Secret: "this is my custom Secret key for internal authorization"
Content-Type: application/json

{
  "UserId": "4ff3fa3b-e69a-47a5-83b6-39a2fe7d4d2a"
}