### Login
POST https://{{identity}}/auth/login
Content-Type: application/json

{
  "userName": "GogiMamu",
  "password": "GogiMamu1@"
}

### Register
POST https://{{identity}}/auth/register
Content-Type: application/json

{
  "username": "GogiMamu",
  "Email": "gogi@gmail.com",
  "Role": "freelancer",
  "password": "GogiMamu1@"
}

### Get User Internally
GET https://{{identity}}/user
Secret: "this is my custom Secret key for internal authorization"
Content-Type: application/json

{
  "UserId": "4ff3fa3b-e69a-47a5-83b6-39a2fe7d4d2a"
}